# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DishPlay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DishPlay

  target 'DishPlayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DishPlayUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'TesseractOCRiOS', '4.0.0'
      post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
    
    source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'

end
